#!/usr/bin/env bash

requests=${3:-10}

validate() {
  if [ -z "$1" ]; then
    source help
    exit 1
  fi

  if [ -z "$2" ]; then
    source help
    exit 1
  fi
}

check () {
  rm cookies.txt
  echo "starting ${requests} requests..."

  start=`date +%s`

  xargs -I % -P 5 curl -H 'user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E304 Safari/602.1' ${1} -I -s < <(printf '%s\n' $(seq 1 ${requests})) | grep -o "${2}" >> cookies.txt

  end=`date +%s`

  echo "finished in $((end-start))s"
  echo
}

validate $@

check $@

source report
