#!/usr/bin/env bash

homes=(masculino feminino casa infantil)
requests=${1:-10}

check () {
  rm ${home}.txt
  echo "starting ${requests} requests to home /${home}/"

  start=`date +%s`

  xargs -I % -P 5 curl -H 'user-agent: Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X) AppleWebKit/603.1.30 (KHTML, like Gecko) Version/10.0 Mobile/14E304 Safari/602.1' https://m.dafiti.com.br/${home}/ -I -s < <(printf '%s\n' $(seq 1 ${requests})) | grep "pwa-[^=]\+=\(new\|old\)" | grep -o "old\|new" >> ${home}.txt

  end=`date +%s`

  echo "finished in $((end-start))s"
  echo
}

for home in "${homes[@]}"
do
  check "$home" 
done

echo "========= REPORT ========="
echo

source report
