#!/usr/bin/env bash

homes=(masculino feminino casa infantil)

echo "|| homepage || qtd new || % new || qtd old || % old ||"
for home in "${homes[@]}"
do
  NEW=$(cat ${home}.txt | grep new | wc -l)
  OLD=$(cat ${home}.txt | grep old | wc -l)
  TOTAL=$((NEW+OLD))
  NEWPERC=$((NEW*100/TOTAL))
  OLDPERC=$((OLD*100/TOTAL))

  echo "| ${home} | ${NEW} | ${NEWPERC} | ${OLD} | ${OLDPERC} |"
done
