#!/usr/bin/env bash

homes=(masculino feminino casa infantil)

for home in "${homes[@]}"
do
  echo $home
  echo "new:" $(cat ${home}.txt | grep new | wc -l)
  echo "old:" $(cat ${home}.txt | grep old | wc -l)
  echo
done
