#!/usr/bin/env bash

eval 'homes=($(cat homes-list.txt))'

for home in "${homes[@]}"
do
  echo $home
  echo "new:" $(cat ${home}-data.txt | grep new | wc -l)
  echo "old:" $(cat ${home}-data.txt | grep old | wc -l)
  echo
done
