#!/usr/bin/env bash

COOKIES=$(cat cookies.txt | sort | uniq)

TOTAL=$(cat cookies.txt | wc -l)

REPORT="De ${TOTAL} requisições:\n"

echo 
for COOKIE in $COOKIES
do
  QTD=$(cat cookies.txt | grep "$COOKIE" | wc -l)
  PERC=$((QTD*100/TOTAL))

  REPORT="${REPORT}${COOKIE} ${QTD} ${PERC}%\n"
done

echo -e $REPORT
